[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
lib_deps =
    bblanchon/ArduinoJson
    iakop/LiquidCrystal_I2C_ESP32
    ; Alternativa compatible con ESP32, pero requiere adaptar Display.cpp:
    ; enjoyneering/LiquidCrystal_I2C
